preload = /home/hathaikorn/Pictures/picture.jpg
preload = /home/hathaikorn/Pictures/picture.jpg

wallpaper {
    monitor = HDMI-A-2
    path = /home/hathaikorn/Pictures/picture.jpg
    fit_mode = cover
}
wallpaper {
    monitor = eDP-1
    path = /home/hathaikorn/Pictures/picture.jpg
    fit_mode = cover
}

splash = false
